apiVersion: v1
kind: Service
metadata:
  name: wedding-fe
  labels:
    app: wedding-fe
spec:
  type: LoadBalancer
  selector:
    app: wedding-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
